CREATE DATABASE HealthClinic;
USE HealthClinic;

CREATE TABLE tb_Clinica(
	IDClinica INT PRIMARY KEY IDENTITY,
	Endereco VARCHAR(100) NOT NULL,
	CPNJ VARCHAR(14) UNIQUE NOT NULL,
	HorarioFuncionamento VARCHAR(20) NOT NULL,
	NomeFantasia VARCHAR(50) NOT NULL,
	RazaoSocial VARCHAR(100) NOT NULL
)

CREATE TABLE tb_Usuario(
	IDUsuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(30) NOT NULL,
	Email VARCHAR(100) UNIQUE NOT NULL,
	Senha VARCHAR(32) NOT NULL,
	Permissao BIT DEFAULT(0)NOT NULL
)

CREATE TABLE tb_Especialidade(
	IDEspecialidade INT PRIMARY KEY IDENTITY,
	NomeEspecialidade VARCHAR(32) NOT NULL
)

CREATE TABLE tb_Medico(
	IDMedico INT PRIMARY KEY IDENTITY,
	IDUsuario INT FOREIGN KEY REFERENCES tb_Usuario(IDUsuario) NOT NULL,
	IDEspecialidade INT FOREIGN KEY REFERENCES tb_Especialidade(IDEspecialidade) NOT NULL,
	IDClinica INT FOREIGN KEY REFERENCES tb_Clinica(IDClinica) NOT NULL,
	CRM VARCHAR(8) UNIQUE NOT NULL
)

CREATE TABLE tb_Paciente(
	IDPaciente INT PRIMARY KEY IDENTITY,
	IDUsuario INT FOREIGN KEY REFERENCES tb_Usuario(IDUsuario) NOT NULL,
	CPF VARCHAR(11) UNIQUE NOT NULL,
	DataNascimento DATE NOT NULL,
	Sexo VARCHAR(10) NOT NULL
)

CREATE TABLE tb_Consulta(
	IDConsulta INT PRIMARY KEY IDENTITY,
	IDPaciente INT FOREIGN KEY REFERENCES tb_Paciente(IDPaciente) NOT NULL,
	IDMedico INT FOREIGN KEY REFERENCES tb_Medico(IDMedico) NOT NULL,
	Descricao VARCHAR(256) NOT NULL,
	[Local] VARCHAR(128) NOT NULL,
	[Data] DATE NOT NULL,
	Horario TIME NOT NULL
)

CREATE TABLE tb_Feedback(
	IDFeedback INT PRIMARY KEY IDENTITY,
	IDConsulta INT FOREIGN KEY REFERENCES tb_Consulta(IDConsulta) NOT NULL,
	IDPaciente INT FOREIGN KEY REFERENCES tb_Paciente(IDPaciente) NOT NULL,
	IDMedico INT FOREIGN KEY REFERENCES tb_Medico(IDMedico) NOT NULL,
	IDClinica INT FOREIGN KEY REFERENCES tb_Clinica(IDClinica) NOT NULL,
	Comentario VARCHAR(256) NOT NULL,
	Nota INT NOT NULL
)
